thirdHWcommit
JustStone/ITproj pull request #4
Opened 2022-11-11 08:25 UTC by JustStone

2022-11-11 10:55 UTC, Vixorem commented
Еще кого то в ревьюверы добавьте

2022-11-11 11:22 UTC, hook171 reviewed
Отличная работа

2022-11-11 11:22 UTC, hook171 commented on Domain/Interfaces/IBaseRepository.cs
>          public T Update(T entity);
Привет

2022-11-11 12:43 UTC, Vixorem requested changes

2022-11-11 12:43 UTC, Vixorem commented on Domain/Interfaces/IReceptionRepository.cs
> +        IEnumerable<DateTime> GetFreeBySpec(Specialization specialization);
Вообще свободные даты логичнее получать на уровне логики. Из бд получать занятые даты и на из основании находить свободные

2022-12-20 10:41 UTC, Vixorem approved these changes

2022-12-20 10:44 UTC, merged